### PR TITLE
fix a bug

### PR DESCRIPTION
**Pull request by bornsky**

### CODE REVIEW

**Comment by YuanZhu-apple** [comment]
Remove the extra "else" make sense to me. 
The files under Asthma.xcodeproj/ should not be included in this commit.

**Comment by bornsky** [comment]
I should have only sent the file that fixed the "else" problem?

**Comment by YuanZhu-apple** [comment]
Yes

**Comment by bornsky** [comment]
I'm not sure how to. Can you point me in the right direction?

**Comment by YuanZhu-apple** [comment]
Just delete the three files and commit.

**Comment by bornsky** [comment]
Give me sometime I don't know what's going on fully just yet

**Comment by YuanZhu-apple** [comment]
Let me close this pull request. 
You can make a new fork and add your change in, then do a new PR.

**Pull request closed without merging**
